name: 'PPC Detective '
favicon: null
layout_spectrum: 0.8159699484240264
typography_spectrum: 0.32462265249341726
title: PPC Detective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56661702-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.926152732456103
  lightness: 0.5830551530234516
  saturation: 0.39646657230332494
  rhythmicContrast: 0.5639141460414976
purpose: []
