name: 'PPC Detective '
favicon: null
layout_spectrum: 0.24794
typography_spectrum: 0.42496
title: PPC Detective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56661702-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6efdd'
    - '#2d2e32'
    - '#3c667c'
    - '#a19f4a'
  brandStrength: 0.926152732456103
  lightness: 0.4375
  saturation: 0.39646657230332494
  rhythmicContrast: 0.5
purpose: []
